import { UserProfile } from './types';

export const FULL_MEMBER_LIST: UserProfile[] = [
  {
    uid: 'mem_1',
    name: 'Abdul Manaff Kemokai',
    role: 'President',
    classification: 'Child Rights',
    joinedDate: '2021-08-15',
    committee: 'Executive Board',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF+3',
    title: 'President',
  },
  {
    uid: 'mem_2',
    name: 'Adonis Abboud',
    role: 'Club Officer',
    classification: 'External Telecommunications',
    joinedDate: '2022-01-06',
    committee: 'Executive Board',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF+1',
  },
  {
    uid: 'mem_3',
    name: 'Afoani Kwaku Ampadu',
    role: 'Club Officer',
    classification: 'Sales & Marketing',
    joinedDate: '2024-07-01',
    committee: 'Membership Committee',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF',
  },
  {
    uid: 'mem_4',
    name: 'Agatha Seriki Vandy',
    role: 'Club Officer',
    classification: 'Education',
    joinedDate: '2024-07-01',
    committee: 'Club Administration Committee',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF',
    title: 'Club Administration Chair',
  },
  {
    uid: 'mem_5',
    name: 'Agnes Ann Wairimu',
    role: 'Club Officer',
    classification: 'HRM & Strategic Management',
    joinedDate: '2024-07-01',
    committee: 'HR & Personnel Committee',
    isPaulHarrisFellow: false,
  },
  {
    uid: 'mem_6',
    name: 'Ahmad Wurie',
    role: 'Rotarian',
    classification: 'Civil Engineering',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_7',
    name: 'Aina Moore',
    role: 'Rotarian',
    classification: 'Commercial Banking & Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_8',
    name: 'Ajara Marie Bomah',
    role: 'Rotarian',
    classification: 'Social Entrepreneur',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_9',
    name: 'Alex Pratt',
    role: 'Rotarian',
    classification: 'Accounting and Finance',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_10',
    name: 'Alex Nallo Jr',
    role: 'Rotarian',
    classification: 'Entrepreneurship',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_11',
    name: 'Alison French',
    role: 'Club Officer',
    classification: 'Communications',
    joinedDate: '2024-07-01',
    committee: 'New Generation Committee',
    title: 'New Generation Chair',
  },
  {
    uid: 'mem_12',
    name: 'Ariana Oluwole',
    role: 'Rotarian',
    classification: 'Edupreneur',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_13',
    name: 'Arnold Dixon',
    role: 'Rotarian',
    classification: 'Banking',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_14',
    name: 'Arthur Johnson',
    role: 'Rotarian',
    classification: 'Consultancy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_15',
    name: 'Avril Ibiduni Renner',
    role: 'Rotarian',
    classification: 'Accounting & Auditing',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_16',
    name: 'Baffour Nketiah-Sarpong',
    role: 'Rotarian',
    classification: 'Chartered Insurance (Insurance Broker)',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_17',
    name: 'Bridget Magoba',
    role: 'Rotarian',
    classification: 'Information Technology',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_18',
    name: 'Cecil Olu-Williams',
    role: 'Rotarian',
    classification: 'Engineer/Systems Administrator',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_19',
    name: 'Cecilia B. Browne',
    role: 'Rotarian',
    classification: 'Education',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_20',
    name: 'Crispin M. Kaikai',
    role: 'Rotarian',
    classification: 'Clergy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_21',
    name: 'Davidson Peters-John',
    role: 'Rotarian',
    classification: 'Finance Consultancy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_22',
    name: 'Emerlin George',
    role: 'Rotarian',
    classification: 'Governance & Administration',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_23',
    name: 'Esther Johnson',
    role: 'Rotarian',
    classification: 'Banking',
    joinedDate: '2022-07-02',
  },
  {
    uid: 'mem_24',
    name: 'Evans Lyndon Baines-Johnson',
    role: 'Club Officer',
    classification: 'Environmental Management',
    joinedDate: '2024-07-01',
    committee: 'Rotary Foundation Committee',
    title: 'Rotary Foundation Chair',
  },
  {
    uid: 'mem_25',
    name: 'Emeka Okechukwu',
    role: 'Rotarian',
    classification: 'Pharmacist',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_26',
    name: 'Fatmata Carew',
    role: 'Rotarian',
    classification: 'Tourism Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_27',
    name: 'Georgette Okyne',
    role: 'Rotarian',
    classification: 'Civil Engineering',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_28',
    name: 'George Marke',
    role: 'Club Officer',
    classification: 'Accounting & Finance',
    joinedDate: '2024-07-01',
    committee: 'Service Projects & Fundraising Committee',
    title: 'Service Projects & Fundraising Chair',
  },
  {
    uid: 'mem_29',
    name: 'Christopher Greene',
    role: 'Rotarian',
    classification: 'Law',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_30',
    name: 'Elijah Koroma',
    role: 'Rotarian',
    classification: 'Technology Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_31',
    name: 'Haja Yeroh Bah',
    role: 'Rotarian',
    classification: 'Public Health',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_32',
    name: 'Ibrahim Bangura',
    role: 'Rotarian',
    classification: 'Law & Governance',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_33',
    name: 'Jane Masaba',
    role: 'Rotarian',
    classification: 'Human Resources & Administration',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_34',
    name: 'Jestina Betts',
    role: 'Club Officer',
    classification: 'Human Resource Management',
    joinedDate: '2024-07-01',
    committee: 'Diaspora Committee',
    title: 'Diaspora Chair',
  },
  {
    uid: 'mem_35',
    name: 'Josephine M Kosia',
    role: 'Club Officer',
    classification: 'Administration',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Secretary',
  },
  {
    uid: 'mem_36',
    name: 'Lauratu Johnson',
    role: 'Rotarian',
    classification: 'Accounting',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_37',
    name: 'Lawrence Sesay',
    role: 'Rotarian',
    classification: 'Information Technology & Systems',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_38',
    name: 'Leslie Gordon-Browne',
    role: 'Rotarian',
    classification: 'Business Development',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_39',
    name: 'Madinatu Senesie-Kamara',
    role: 'Rotarian',
    classification: 'International Civil Service',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_40',
    name: 'Musyoka E. Mutulya',
    role: 'Club Officer',
    classification: 'Accounting and Finance',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Sergeant-at-Arms',
  },
  {
    uid: 'mem_41',
    name: 'Mariama Sesay',
    role: 'Rotarian',
    classification: 'Pharmaceutical Operations',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_42',
    name: 'Mariama Ruth Jacinta Jaysid-Sankoh',
    role: 'Rotarian',
    classification: 'Law',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_43',
    name: 'Melphina Beoku-Betts',
    role: 'Club Officer',
    classification: 'Education',
    joinedDate: '2024-07-01',
    committee: 'Membership Committee',
    title: 'Membership Chair',
  },
  {
    uid: 'mem_44',
    name: 'Miatta French',
    role: 'Rotarian',
    classification: 'Electoral Administration',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_45',
    name: 'Michaela Serry',
    role: 'Rotarian',
    classification: 'Corporate Law',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_46',
    name: 'Millicent Cole',
    role: 'Club Officer',
    classification: 'Corporate Banking',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Vice President',
  },
  {
    uid: 'mem_47',
    name: 'Musa Bernard Komeh',
    role: 'Club Officer',
    classification: 'Global Public Health',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Immediate Past President',
  },
  {
    uid: 'mem_48',
    name: 'Musa Mansaray',
    role: 'Rotarian',
    classification: 'Procurement and Supply Chain Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_49',
    name: 'Noel Atere-Roberts',
    role: 'Rotarian',
    classification: 'IT & Real Estate Consultancy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_50',
    name: 'Pauline Wanjiru Kibe',
    role: 'Rotarian',
    classification: 'Project Management',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_51',
    name: 'Saio Yanka',
    role: 'Club Officer',
    classification: 'Tax and Accounting',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Treasurer',
  },
  {
    uid: 'mem_52',
    name: 'Sallieu Kanu',
    role: 'Rotarian',
    classification: 'Business Development',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_53',
    name: 'Sam Kumbo Leigh',
    role: 'Rotarian',
    classification: 'Business Management',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_54',
    name: 'Stephen Kabba',
    role: 'Rotarian',
    classification: 'Network Technology',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_55',
    name: 'Sylvia Fasuluku',
    role: 'Rotarian',
    classification: 'Medicine',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_56',
    name: 'Ufuoma Festus Omo-Obi',
    role: 'Rotarian',
    classification: 'Health Systems & Development Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_57',
    name: 'Victor Williams',
    role: 'Club Officer',
    classification: 'Banking',
    joinedDate: '2022-03-16',
    committee: 'Executive Board',
    title: 'President Elect',
  },
  {
    uid: 'mem_58',
    name: 'Wilhemina Sho-Cole',
    role: 'Rotarian',
    classification: 'Governance Programme',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_59',
    name: 'Yasmine Ibrahim',
    role: 'Club Officer',
    classification: 'Content Creation',
    joinedDate: '2024-07-01',
    committee: 'Public Image Committee',
    title: 'Public Image Chair',
  },
  {
    uid: 'mem_60',
    name: 'Manja Abdulai',
    role: 'Rotarian',
    classification: 'Public Administration'
  }
];
