import { UserProfile } from './types';

export const FULL_MEMBER_LIST: UserProfile[] = [
  {
    uid: 'mem_1',
    name: 'Abdul Manafi Kemokai',
    email: 'am••••••@yahoo.co.uk',
    phone: '+232 76 ••• •61',
    role: 'President',
    classification: 'Child Rights',
    joinedDate: '2021-08-15',
    birthday: '13th December',
    attendanceRate: 98,
    contributionGoals: 2000,
    contributedAmount: 2000,
    committee: 'Executive Board',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF+3',
    tasks: ['Chair weekly board synergy meetings', 'Coordinate clean water well expansion']
  },
  {
    uid: 'mem_2',
    name: 'Adonis Abboud',
    email: 'di••••••@yahoo.com',
    phone: '+232 76 ••• •74',
    role: 'Club Officer',
    classification: 'External Telecommunications',
    joinedDate: '2022-03-10',
    birthday: '5th March',
    attendanceRate: 95,
    contributionGoals: 1500,
    contributedAmount: 1200,
    committee: 'Executive Board',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF+1',
    tasks: ['Manage international telecommunication relations', 'Oversee Bintumani Charity auction list']
  },
  {
    uid: 'mem_3',
    name: 'Afouni Kwaku Ampadu',
    email: 'ka••••••@gmail.com',
    phone: '+232 79 ••• •64',
    role: 'Club Officer',
    classification: 'Sales & Marketing',
    joinedDate: '2024-07-01',
    birthday: '29th May',
    attendanceRate: 91,
    contributionGoals: 1000,
    contributedAmount: 800,
    committee: 'Membership Committee',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF',
    tasks: ['Organize weekly beachside fellowship hours', 'Run guest orientations for prospective leaders']
  },
  {
    uid: 'mem_4',
    name: 'Agatha Seriki-Yandy',
    email: 'se••••••@gmail.com',
    phone: '+232 76 ••• •49',
    role: 'Club Officer',
    classification: 'Education',
    joinedDate: '2024-07-01',
    birthday: '18th May',
    attendanceRate: 94,
    contributionGoals: 1000,
    contributedAmount: 1000,
    committee: 'Youth & Education Committee',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF',
    tasks: ['Supervise secondary literacy library programs', 'Manage school leading scores audit']
  },
  {
    uid: 'mem_5',
    name: 'Agnes Ann Wairimu',
    email: 'ag••••••@gmail.com',
    phone: '+232 78 ••• •86',
    role: 'Club Officer',
    classification: 'HRM & Strategic Management',
    joinedDate: '2024-07-01',
    birthday: '29th June',
    attendanceRate: 92,
    contributionGoals: 1000,
    contributedAmount: 900,
    committee: 'HR & Personnel Committee',
    isPaulHarrisFellow: false,
    tasks: ['Support vocational training coordinator sessions', 'Coordinate annual committee resources']
  },
  {
    uid: 'mem_6',
    name: 'Ahmad Wurie',
    email: 'ah••••••@shiac.ltd',
    phone: '+232 76 ••• •71',
    role: 'Rotarian',
    classification: 'Civil Engineering',
    joinedDate: '2024-07-01',
    birthday: '30th May'
  },
  {
    uid: 'mem_7',
    name: 'Aina Moore',
    email: 'mo••••••@yahoo.com',
    phone: '+232 34 ••• •40',
    role: 'Rotarian',
    classification: 'Commercial Banking & Management',
    joinedDate: '2024-07-01',
    birthday: '28th June'
  },
  {
    uid: 'mem_8',
    name: 'Ajara Marie Bomah',
    email: 'ad••••••@gmail.com',
    phone: '+232 79 ••• •55',
    role: 'Rotarian',
    classification: 'Social Entrepreneur',
    joinedDate: '2024-07-01',
    birthday: '20th January'
  },
  {
    uid: 'mem_9',
    name: 'Alex Pratt',
    email: 'ch••••••@yahoo.com',
    phone: '+232 76 ••• •40',
    role: 'Rotarian',
    classification: 'Accounting and Finance',
    joinedDate: '2024-07-01',
    birthday: '15th May'
  },
  {
    uid: 'mem_10',
    name: 'Alex Nallo Jnr',
    email: 'al••••••@yahoo.com',
    phone: '+232 33 ••• •03',
    role: 'Rotarian',
    classification: 'Entrepreneurship',
    joinedDate: '2024-07-01',
    birthday: '22nd October'
  },
  {
    uid: 'mem_11',
    name: 'Alison French',
    email: 'al••••••@gmail.com',
    phone: '+232 78 ••• •11',
    role: 'Rotarian',
    classification: 'Communications',
    joinedDate: '2024-07-01',
    birthday: '21st May'
  },
  {
    uid: 'mem_12',
    name: 'Amara Oluwole',
    email: 'am••••••@gmail.com',
    phone: '+232 76 ••• •48',
    role: 'Rotarian',
    classification: 'Edutrepreneur',
    joinedDate: '2024-07-01',
    birthday: '17th February'
  },
  {
    uid: 'mem_13',
    name: 'Arnold Dixon',
    email: 'ad••••••@gmail.com',
    phone: '+232 77 ••• •97',
    role: 'Rotarian',
    classification: 'Banking',
    joinedDate: '2024-07-01',
    birthday: '18th September'
  },
  {
    uid: 'mem_14',
    name: 'Arthur Johnson',
    email: 'sa••••••@gmail.com',
    phone: '+232 76 ••• •99',
    role: 'Rotarian',
    classification: 'Consultancy',
    joinedDate: '2024-07-01',
    birthday: '6th November'
  },
  {
    uid: 'mem_15',
    name: 'Avril Beduni Renner',
    email: 'br••••••@yahoo.com',
    phone: '+232 76 ••• •71',
    role: 'Rotarian',
    classification: 'Accounting & Auditing',
    joinedDate: '2024-07-01',
    birthday: '27th April'
  },
  {
    uid: 'mem_16',
    name: 'Balfour Nketiah-Sarpong',
    email: 'bn••••••@glicgroup.net',
    phone: '+232 78 ••• •88',
    role: 'Rotarian',
    classification: 'Chartered Insurance (Insurance Broker)',
    joinedDate: '2024-07-01',
    birthday: '15th June'
  },
  {
    uid: 'mem_17',
    name: 'Bridget Mogobo',
    email: 'br••••••@gmail.com',
    phone: '+232 76 ••• •36',
    role: 'Rotarian',
    classification: 'Information Technology',
    joinedDate: '2024-07-01',
    birthday: '17th October'
  },
  {
    uid: 'mem_18',
    name: 'Cecil Olo-Williams',
    email: 'ce••••••@gmail.com',
    phone: '+232 76 ••• •05',
    role: 'Rotarian',
    classification: 'Engineer/Systems Administrator',
    joinedDate: '2024-07-01',
    birthday: '26th December'
  },
  {
    uid: 'mem_19',
    name: 'Cecilia B. Browne',
    email: 'cb••••••@gmail.com',
    phone: '+232 76 ••• •96',
    role: 'Rotarian',
    classification: 'Education',
    joinedDate: '2024-07-01',
    birthday: '14th September'
  },
  {
    uid: 'mem_20',
    name: 'Davidson Peters-John',
    email: 'dp••••••@yahoo.com',
    phone: '+232 90 ••• •47',
    role: 'Rotarian',
    classification: 'Finance Consultancy',
    joinedDate: '2024-07-01',
    birthday: '8th July'
  },
  {
    uid: 'mem_21',
    name: 'Emerlin George',
    email: 'di••••••@gmail.com',
    phone: '+232 76 ••• •27',
    role: 'Rotarian',
    classification: 'Governance & Administration',
    joinedDate: '2024-07-01',
    birthday: '17th July'
  },
  {
    uid: 'mem_22',
    name: 'Esther Johnson',
    email: 'ej••••••@fsb.com.sl',
    phone: '+232 76 ••• •91',
    role: 'Rotarian',
    classification: 'Banking',
    joinedDate: '2024-07-01',
    birthday: '1st October'
  },
  {
    uid: 'mem_23',
    name: 'Fatmata Carew',
    email: 'fa••••••@yahoo.com',
    phone: '+232 76 ••• •45',
    role: 'Rotarian',
    classification: 'Tourism Management',
    joinedDate: '2024-07-01',
    birthday: '11th May'
  },
  {
    uid: 'mem_24',
    name: 'Georgette Okyne',
    email: 'ge••••••@yahoo.com',
    phone: '+232 76 ••• •83',
    role: 'Rotarian',
    classification: 'Civil Engineering',
    joinedDate: '2024-07-01',
    birthday: '17th April'
  },
  {
    uid: 'mem_25',
    name: 'Haja Yeroh Bah',
    email: 'ha••••••@gmail.com',
    phone: '+232 75 ••• •68',
    role: 'Rotarian',
    classification: 'Public Health',
    joinedDate: '2024-07-01',
    birthday: '25th July'
  },
  {
    uid: 'mem_26',
    name: 'Ibrahim Bangura',
    email: 'ib••••••@gmail.com',
    phone: '+232 78 ••• •66',
    role: 'Rotarian',
    classification: 'Law & Governance',
    joinedDate: '2024-07-01',
    birthday: '1st May'
  },
  {
    uid: 'mem_27',
    name: 'Jane Masobu',
    email: 'mu••••••@gmail.com',
    phone: '+232 79 ••• •55',
    role: 'Rotarian',
    classification: 'Human Resources & Administration',
    joinedDate: '2024-07-01',
    birthday: '20th March'
  },
  {
    uid: 'mem_28',
    name: 'Jestina Betts',
    email: 'je••••••@orange-sonatel.com',
    phone: '+232 76 ••• •93',
    role: 'Rotarian',
    classification: 'Human Resource Management',
    joinedDate: '2024-07-01',
    birthday: '6th November'
  },
  {
    uid: 'mem_29',
    name: 'Lauratu Johnson',
    email: 'li••••••@hotmail.com',
    phone: '+232 76 ••• •07',
    role: 'Rotarian',
    classification: 'Accounting',
    joinedDate: '2024-07-01',
    birthday: '17th August'
  },
  {
    uid: 'mem_30',
    name: 'Lawrence Sesay',
    email: 'la••••••@gmail.com',
    phone: '+232 76 ••• •03',
    role: 'Rotarian',
    classification: 'Information Technology & Systems',
    joinedDate: '2024-07-01',
    birthday: '30th April'
  },
  {
    uid: 'mem_31',
    name: 'Leslie Gordon-Browne',
    email: 'le••••••@gmail.com',
    phone: '+232 79 ••• •82',
    role: 'Rotarian',
    classification: 'Business Development',
    joinedDate: '2024-07-01',
    birthday: '24th December'
  },
  {
    uid: 'mem_32',
    name: 'Mudunotu Senesie-Kamara',
    email: 'mu••••••@gmail.com',
    phone: '4478••••••55',
    role: 'Rotarian',
    classification: 'International Social Service',
    joinedDate: '2024-07-01',
    birthday: '14th July'
  },
  {
    uid: 'mem_33',
    name: 'Munya Abdulai',
    email: 'mu••••••@gmail.com',
    phone: '+232 76 ••• •60',
    role: 'Rotarian',
    classification: 'Public Administration',
    joinedDate: '2024-07-01',
    birthday: '19th November'
  },
  {
    uid: 'mem_34',
    name: 'Mariama Sesay',
    email: 'ma••••••@gmail.com',
    phone: '+232 76 ••• •04',
    role: 'Rotarian',
    classification: 'Pharmaceutical Operations',
    joinedDate: '2024-07-01',
    birthday: '9th September'
  },
  {
    uid: 'mem_35',
    name: 'Mariama Ruth Jacinta Jassik-Sankoh',
    email: 'ma••••••@gmail.com',
    phone: '+232 •• ••• •••',
    role: 'Rotarian',
    classification: 'Law',
    joinedDate: '2024-07-01',
    birthday: '12th May'
  },
  {
    uid: 'mem_36',
    name: 'Melvina Brocke-Betts',
    email: 'mb••••••@hotmail.co.uk',
    phone: '+232 78 ••• •71',
    role: 'Rotarian',
    classification: 'Education',
    joinedDate: '2024-07-01',
    birthday: '11th June'
  },
  {
    uid: 'mem_37',
    name: 'Miatta French',
    email: 'mi••••••@yahoo.com',
    phone: '+232 76 ••• •41',
    role: 'Rotarian',
    classification: 'Electoral Administration',
    joinedDate: '2024-07-01',
    birthday: '14th July'
  },
  {
    uid: 'mem_38',
    name: 'Michaela Serry',
    email: 'co••••••@yahoo.com',
    phone: '+232 79 ••• •75',
    role: 'Rotarian',
    classification: 'Corporate Law',
    joinedDate: '2024-07-01',
    birthday: '26th November'
  },
  {
    uid: 'mem_39',
    name: 'Millicent Cole',
    email: 'mk••••••@hotmail.com',
    phone: '+232 76 ••• •13',
    role: 'Rotarian',
    classification: 'Corporate Banking',
    joinedDate: '2024-07-01',
    birthday: '15th November'
  },
  {
    uid: 'mem_40',
    name: 'Myra Bernard Stevens',
    email: 'my••••••@gmail.com',
    phone: '+232 76 ••• •32',
    role: 'Rotarian',
    classification: 'Global Public Health',
    joinedDate: '2024-07-01',
    birthday: '19th March'
  },
  {
    uid: 'mem_41',
    name: 'Manyoka E. Mutulya',
    email: 'ma••••••@gmail.com',
    phone: '+232 76 ••• •10',
    role: 'Rotarian',
    classification: 'Accounting and Finance',
    joinedDate: '2024-07-01',
    birthday: '15th August'
  },
  {
    uid: 'mem_42',
    name: 'Noel Asare-Roberts',
    email: 'am••••••@gmail.com',
    phone: '+232 76 ••• •78',
    role: 'Rotarian',
    classification: 'IT & Real Estate Consultancy',
    joinedDate: '2024-07-01',
    birthday: '23rd December'
  },
  {
    uid: 'mem_43',
    name: 'Pauline Wanjiru Kibe',
    email: 'ki••••••@gmail.com',
    phone: '+232 78 ••• •83',
    role: 'Rotarian',
    classification: 'Project management',
    joinedDate: '2024-07-01',
    birthday: '24th January'
  },
  {
    uid: 'mem_44',
    name: 'Sajo Yanku',
    email: 'sa••••••@yahoo.com',
    phone: '+232 76 ••• •50',
    role: 'Rotarian',
    classification: 'Tax and Accounting',
    joinedDate: '2024-07-01',
    birthday: '26th January'
  },
  {
    uid: 'mem_45',
    name: 'Sallieu Kanu',
    email: 'sa••••••@yahoo.com',
    phone: '+232 76 ••• •73',
    role: 'Rotarian',
    classification: 'Business Development',
    joinedDate: '2024-07-01',
    birthday: '31st October'
  },
  {
    uid: 'mem_46',
    name: 'Sam Kumbo-Leigh',
    email: 'sk••••••@edu-fld.org',
    phone: '+232 79 ••• •49',
    role: 'Rotarian',
    classification: 'Business Management',
    joinedDate: '2024-07-01',
    birthday: '15th July'
  },
  {
    uid: 'mem_47',
    name: 'Stephen Kabba',
    email: 'be••••••@yahoo.com',
    phone: '+232 76 ••• •39',
    role: 'Rotarian',
    classification: 'Network Technology',
    joinedDate: '2024-07-01',
    birthday: '17th July'
  },
  {
    uid: 'mem_48',
    name: 'Sylvia Fusu-luki',
    email: 'sy••••••@gmail.com',
    phone: '+232 78 ••• •04',
    role: 'Rotarian',
    classification: 'Medicine',
    joinedDate: '2024-07-01',
    birthday: '18th May'
  },
  {
    uid: 'mem_49',
    name: 'Ulaoma Festus Omo-Obi',
    email: 'ul••••••@yahoo.com',
    phone: '+232 78 ••• •53',
    role: 'Rotarian',
    classification: 'Health Systems & Development Management',
    joinedDate: '2024-07-01',
    birthday: '8th March'
  },
  {
    uid: 'mem_50',
    name: 'Victor Williams',
    email: 'vw••••••@gmail.com',
    phone: '+232 88 ••• •20',
    role: 'Rotarian',
    classification: 'Banking',
    joinedDate: '2024-07-01',
    birthday: '20th August'
  },
  {
    uid: 'mem_51',
    name: 'Wilhelmina Sho-Cole',
    email: 'mi••••••@yahoo.com',
    phone: '+232 76 ••• •96',
    role: 'Rotarian',
    classification: 'Governance/Programme',
    joinedDate: '2024-07-01',
    birthday: '9th July'
  },
  {
    uid: 'mem_52',
    name: 'Yasmine Ibrahim',
    email: 'in••••••@minabilikis.com',
    phone: '+232 78 ••• •81',
    role: 'Rotarian',
    classification: 'Content Creation',
    joinedDate: '2024-07-01',
    birthday: '28th November'
  },
  {
    uid: 'mem_53',
    name: 'Josephine Konia',
    email: 'jo••••••@gmail.com',
    phone: '+232 79 ••• •55',
    role: 'Rotarian',
    classification: 'Administration',
    joinedDate: '2024-07-01',
    birthday: '20th March'
  },
  {
    uid: 'mem_54',
    name: 'Musa Mansaray',
    email: 'mu••••••@yahoo.co.uk',
    phone: '+232 75 ••• •73',
    role: 'Rotarian',
    classification: 'Procurement and Supply Chain Management Specialists',
    joinedDate: '2024-07-01',
    birthday: '28th November'
  },
  {
    uid: 'mem_55',
    name: 'George Marke',
    email: 'fm••••••@gmail.com',
    phone: '+232 78 ••• •07',
    role: 'Rotarian',
    classification: 'Accounting and Finance',
    joinedDate: '2024-07-01',
    birthday: '21st January'
  },
  {
    uid: 'mem_56',
    name: 'Evans Lyndon Baine-Johnson',
    email: 'ev••••••@yahoo.com',
    phone: '+232 78 ••• •03',
    role: 'Rotarian',
    classification: 'Environmental Management',
    joinedDate: '2024-07-01',
    birthday: '25th September'
  },
  {
    uid: 'mem_57',
    name: 'Emeka Okechuwa',
    email: 'em••••••@gmail.com',
    phone: '+232 34 ••• •37',
    role: 'Rotarian',
    classification: 'Pharmacist',
    joinedDate: '2024-07-01',
    birthday: '27th February'
  },
  {
    uid: 'mem_58',
    name: 'Crispin M. Kaikai',
    email: 'k_••••••@icloud.com',
    phone: '+232 76 ••• •02',
    role: 'Rotarian',
    classification: 'Clergy',
    joinedDate: '2024-07-01',
    birthday: '17th November'
  },
  {
    uid: 'mem_59',
    name: 'Elijah Koroma',
    email: 'el••••••@live.co.uk',
    phone: '+232 79 ••• •23',
    role: 'Rotarian',
    classification: 'Technology Management',
    joinedDate: '2024-07-01',
    birthday: '12th March'
  }
];
