import { UserProfile } from './types';

import abdulPhoto from './assets/images/member_abdul_manafe_1783806739015.jpg';
import millicentPhoto from './assets/images/member_millicent_cole_1783806748849.jpg';
import victorPhoto from './assets/images/member_victor_williams_1783806759314.jpg';
import musaPhoto from './assets/images/member_musa_komeh_1783806767366.jpg';
import josephinePhoto from './assets/images/member_josephine_kosia_1783806778446.jpg';
import saioPhoto from './assets/images/member_saio_yanka_1783806789121.jpg';
import ericPhoto from './assets/images/member_eric_mutulya_1783806797638.jpg';
import yasminePhoto from './assets/images/member_yasmine_ibrahim_1783806809698.jpg';
import georgePhoto from './assets/images/member_george_marke_1783806818919.jpg';
import alisonPhoto from './assets/images/member_alison_french_1783806826773.jpg';
import agathaPhoto from './assets/images/member_agatha_vandy_1783806836273.jpg';
import melphinaPhoto from './assets/images/member_melphina_betts_1783806846432.jpg';
import jestinaPhoto from './assets/images/member_jestina_betts_1783806855527.jpg';
import lyndonPhoto from './assets/images/member_lyndon_johnson_1783806863939.jpg';

export const FULL_MEMBER_LIST: UserProfile[] = [
  {
    uid: 'mem_1',
    name: 'Abdul Manaff Kemokai',
    role: 'President',
    classification: 'Child Rights',
    joinedDate: '2021-08-15',
    attendanceRate: 98,
    contributionGoals: 2000,
    contributedAmount: 2000,
    committee: 'Executive Board',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF+3',
    tasks: ['Chair weekly board synergy meetings', 'Coordinate clean water well expansion'],
    title: 'President',
    avatarUrl: abdulPhoto
  },
  {
    uid: 'mem_2',
    name: 'Adonis Abboud',
    role: 'Club Officer',
    classification: 'External Telecommunications',
    joinedDate: '2022-01-06',
    attendanceRate: 95,
    contributionGoals: 1500,
    contributedAmount: 1200,
    committee: 'Executive Board',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF+1',
    tasks: ['Manage international telecommunication relations', 'Oversee Bintumani Charity auction list']
  },
  {
    uid: 'mem_3',
    name: 'Afoani Kwaku Ampadu',
    role: 'Club Officer',
    classification: 'Sales & Marketing',
    joinedDate: '2024-07-01',
    attendanceRate: 91,
    contributionGoals: 1000,
    contributedAmount: 800,
    committee: 'Membership Committee',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF',
    tasks: ['Organize weekly beachside fellowship hours', 'Run guest orientations for prospective leaders']
  },
  {
    uid: 'mem_4',
    name: 'Agatha Seriki Vandy',
    role: 'Club Officer',
    classification: 'Education',
    joinedDate: '2024-07-01',
    attendanceRate: 94,
    contributionGoals: 1000,
    contributedAmount: 1000,
    committee: 'Club Administration Committee',
    isPaulHarrisFellow: true,
    paulHarrisLevel: 'PHF',
    tasks: ['Supervise secondary literacy library programs', 'Manage school leading scores audit'],
    title: 'Club Administration Chair',
    avatarUrl: agathaPhoto
  },
  {
    uid: 'mem_5',
    name: 'Agnes Ann Wairimu',
    role: 'Club Officer',
    classification: 'HRM & Strategic Management',
    joinedDate: '2024-07-01',
    attendanceRate: 92,
    contributionGoals: 1000,
    contributedAmount: 900,
    committee: 'HR & Personnel Committee',
    isPaulHarrisFellow: false,
    tasks: ['Support vocational training coordinator sessions', 'Coordinate annual committee resources']
  },
  {
    uid: 'mem_6',
    name: 'Ahmad Wurie',
    role: 'Rotarian',
    classification: 'Civil Engineering',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_7',
    name: 'Aina Moore',
    role: 'Rotarian',
    classification: 'Commercial Banking & Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_8',
    name: 'Ajara Marie Bomah',
    role: 'Rotarian',
    classification: 'Social Entrepreneur',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_9',
    name: 'Alex Pratt',
    role: 'Rotarian',
    classification: 'Accounting and Finance',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_10',
    name: 'Alex Nallo Jr',
    role: 'Rotarian',
    classification: 'Entrepreneurship',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_11',
    name: 'Alison French',
    role: 'Club Officer',
    classification: 'Communications',
    joinedDate: '2024-07-01',
    committee: 'New Generation Committee',
    title: 'New Generation Chair',
    avatarUrl: alisonPhoto
  },
  {
    uid: 'mem_12',
    name: 'Ariana Oluwole',
    role: 'Rotarian',
    classification: 'Edupreneur',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_13',
    name: 'Arnold Dixon',
    role: 'Rotarian',
    classification: 'Banking',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_14',
    name: 'Arthur Johnson',
    role: 'Rotarian',
    classification: 'Consultancy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_15',
    name: 'Avril Ibiduni Renner',
    role: 'Rotarian',
    classification: 'Accounting & Auditing',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_16',
    name: 'Baffour Nketiah-Sarpong',
    role: 'Rotarian',
    classification: 'Chartered Insurance (Insurance Broker)',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_17',
    name: 'Bridget Magoba',
    role: 'Rotarian',
    classification: 'Information Technology',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_18',
    name: 'Cecil Olu-Williams',
    role: 'Rotarian',
    classification: 'Engineer/Systems Administrator',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_19',
    name: 'Cecilia B. Browne',
    role: 'Rotarian',
    classification: 'Education',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_20',
    name: 'Crispin M. Kaikai',
    role: 'Rotarian',
    classification: 'Clergy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_21',
    name: 'Davidson Peters-John',
    role: 'Rotarian',
    classification: 'Finance Consultancy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_22',
    name: 'Emerlin George',
    role: 'Rotarian',
    classification: 'Governance & Administration',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_23',
    name: 'Esther Johnson',
    role: 'Rotarian',
    classification: 'Banking',
    joinedDate: '2022-07-02',
  },
  {
    uid: 'mem_24',
    name: 'Evans Lyndon Baines-Johnson',
    role: 'Club Officer',
    classification: 'Environmental Management',
    joinedDate: '2024-07-01',
    committee: 'Rotary Foundation Committee',
    title: 'Rotary Foundation Chair',
    avatarUrl: lyndonPhoto
  },
  {
    uid: 'mem_25',
    name: 'Emeka Okechukwu',
    role: 'Rotarian',
    classification: 'Pharmacist',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_26',
    name: 'Fatmata Carew',
    role: 'Rotarian',
    classification: 'Tourism Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_27',
    name: 'Georgette Okyne',
    role: 'Rotarian',
    classification: 'Civil Engineering',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_28',
    name: 'George Marke',
    role: 'Club Officer',
    classification: 'Accounting & Finance',
    joinedDate: '2024-07-01',
    committee: 'Service Projects & Fundraising Committee',
    title: 'Service Projects & Fundraising Chair',
    avatarUrl: georgePhoto
  },
  {
    uid: 'mem_29',
    name: 'Christopher Greene',
    role: 'Rotarian',
    classification: 'Law',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_30',
    name: 'Elijah Koroma',
    role: 'Rotarian',
    classification: 'Technology Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_31',
    name: 'Haja Yeroh Bah',
    role: 'Rotarian',
    classification: 'Public Health',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_32',
    name: 'Ibrahim Bangura',
    role: 'Rotarian',
    classification: 'Law & Governance',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_33',
    name: 'Jane Masaba',
    role: 'Rotarian',
    classification: 'Human Resources & Administration',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_34',
    name: 'Jestina Betts',
    role: 'Club Officer',
    classification: 'Human Resource Management',
    joinedDate: '2024-07-01',
    committee: 'Diaspora Committee',
    title: 'Diaspora Chair',
    avatarUrl: jestinaPhoto
  },
  {
    uid: 'mem_35',
    name: 'Josephine M Kosia',
    role: 'Club Officer',
    classification: 'Administration',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Secretary',
    avatarUrl: josephinePhoto
  },
  {
    uid: 'mem_36',
    name: 'Lauratu Johnson',
    role: 'Rotarian',
    classification: 'Accounting',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_37',
    name: 'Lawrence Sesay',
    role: 'Rotarian',
    classification: 'Information Technology & Systems',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_38',
    name: 'Leslie Gordon-Browne',
    role: 'Rotarian',
    classification: 'Business Development',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_39',
    name: 'Madinatu Senesie-Kamara',
    role: 'Rotarian',
    classification: 'International Civil Service',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_40',
    name: 'Musyoka E. Mutulya',
    role: 'Club Officer',
    classification: 'Accounting and Finance',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Sergeant-at-Arms',
    avatarUrl: ericPhoto
  },
  {
    uid: 'mem_41',
    name: 'Mariama Sesay',
    role: 'Rotarian',
    classification: 'Pharmaceutical Operations',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_42',
    name: 'Mariama Ruth Jacinta Jaysid-Sankoh',
    role: 'Rotarian',
    classification: 'Law',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_43',
    name: 'Melphina Beoku-Betts',
    role: 'Club Officer',
    classification: 'Education',
    joinedDate: '2024-07-01',
    committee: 'Membership Committee',
    title: 'Membership Chair',
    avatarUrl: melphinaPhoto
  },
  {
    uid: 'mem_44',
    name: 'Miatta French',
    role: 'Rotarian',
    classification: 'Electoral Administration',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_45',
    name: 'Michaela Serry',
    role: 'Rotarian',
    classification: 'Corporate Law',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_46',
    name: 'Millicent Cole',
    role: 'Club Officer',
    classification: 'Corporate Banking',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Vice President',
    avatarUrl: millicentPhoto
  },
  {
    uid: 'mem_47',
    name: 'Musa Bernard Komeh',
    role: 'Club Officer',
    classification: 'Global Public Health',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Immediate Past President',
    avatarUrl: musaPhoto
  },
  {
    uid: 'mem_48',
    name: 'Musa Mansaray',
    role: 'Rotarian',
    classification: 'Procurement and Supply Chain Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_49',
    name: 'Noel Atere-Roberts',
    role: 'Rotarian',
    classification: 'IT & Real Estate Consultancy',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_50',
    name: 'Pauline Wanjiru Kibe',
    role: 'Rotarian',
    classification: 'Project Management',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_51',
    name: 'Saio Yanka',
    role: 'Club Officer',
    classification: 'Tax and Accounting',
    joinedDate: '2024-07-01',
    committee: 'Executive Board',
    title: 'Treasurer',
    avatarUrl: saioPhoto
  },
  {
    uid: 'mem_52',
    name: 'Sallieu Kanu',
    role: 'Rotarian',
    classification: 'Business Development',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_53',
    name: 'Sam Kumbo Leigh',
    role: 'Rotarian',
    classification: 'Business Management',
    joinedDate: '2022-03-16',
  },
  {
    uid: 'mem_54',
    name: 'Stephen Kabba',
    role: 'Rotarian',
    classification: 'Network Technology',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_55',
    name: 'Sylvia Fasuluku',
    role: 'Rotarian',
    classification: 'Medicine',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_56',
    name: 'Ufuoma Festus Omo-Obi',
    role: 'Rotarian',
    classification: 'Health Systems & Development Management',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_57',
    name: 'Victor Williams',
    role: 'Club Officer',
    classification: 'Banking',
    joinedDate: '2022-03-16',
    committee: 'Executive Board',
    title: 'President Elect',
    avatarUrl: victorPhoto
  },
  {
    uid: 'mem_58',
    name: 'Wilhemina Sho-Cole',
    role: 'Rotarian',
    classification: 'Governance Programme',
    joinedDate: '2024-07-01',
  },
  {
    uid: 'mem_59',
    name: 'Yasmine Ibrahim',
    role: 'Club Officer',
    classification: 'Content Creation',
    joinedDate: '2024-07-01',
    committee: 'Public Image Committee',
    title: 'Public Image Chair',
    avatarUrl: yasminePhoto
  },
  {
    uid: 'mem_60',
    name: 'Manja Abdulai',
    role: 'Rotarian',
    classification: 'Public Administration'
  }
];
